/**
 * AK's MEN STYLE — Master 100 Products Catalog
 * IDs 1-100:
 * - 40 Tops (1-20 Shirts & T-Shirts, 31-40 Hoodies, 41-50 Jackets)
 * - 10 Bottoms (21-30 Curated Trousers & Pants)
 * - 50 Accessories (51-60 Shoes, 61-70 Watches, 71-80 Caps, 81-90 Belts, 91-100 Sunglasses)
 */

export const productsData = [
  // ===================== TOPS: SHIRTS & T-SHIRTS (1 - 20) =====================
  {
    id: 1,
    name: "Classic Oxford Slim-Fit Shirt",
    description: "Premium cotton Oxford weave with tailored slim fit and button-down collar.",
    brand: "AK Signature",
    category: "Shirts",
    cloth_type: "Oxford Shirt",
    color: "Crisp White",
    price: 599,
    original_price: 799,
    discount_percent: 25,
    stock: 8,
    status: "IN_STOCK",
    image: "/images/products/product_1.png",
    garment_image: "/images/garments/product_1.png",
    vton_supported: 1,
    vton_garment_category: "tops"
  },
  {
    id: 2,
    name: "Tailored Navy Chambray Shirt",
    description: "Soft washed indigo chambray shirt with modern curved hem and contrast stitching.",
    brand: "AK Urban",
    category: "Shirts",
    cloth_type: "Casual Shirt",
    color: "Navy Blue",
    price: 595,
    original_price: 850,
    discount_percent: 30,
    stock: 7,
    status: "IN_STOCK",
    image: "/images/products/product_2.png",
    garment_image: "/images/garments/product_2.png",
    vton_supported: 1,
    vton_garment_category: "tops"
  },
  {
    id: 3,
    name: "Charcoal Textured Business Shirt",
    description: "Wrinkle-resistant pinpoint weave crafted for structured professional elegance.",
    brand: "AK Atelier",
    category: "Shirts",
    cloth_type: "Business Shirt",
    color: "Charcoal Grey",
    price: 618,
    original_price: 950,
    discount_percent: 35,
    stock: 5,
    status: "IN_STOCK",
    image: "/images/products/product_3.png",
    garment_image: "/images/garments/product_3.png",
    vton_supported: 1,
    vton_garment_category: "tops"
  },
  {
    id: 4,
    name: "Relaxed Linen Cuban Collar Shirt",
    description: "Airy lightweight linen shirt with retro revere collar for effortless warmth.",
    brand: "AK Studio",
    category: "Shirts",
    cloth_type: "Cuban Collar Shirt",
    color: "Olive Drab",
    price: 629,
    original_price: 899,
    discount_percent: 30,
    stock: 6,
    status: "IN_STOCK",
    image: "/images/products/product_4.png",
    garment_image: "/images/garments/product_4.png",
    vton_supported: 1,
    vton_garment_category: "tops"
  },
  {
    id: 5,
    name: "Minimalist Jet Black Poplin Shirt",
    description: "Clean hidden placket dress shirt made from long-staple Egyptian cotton.",
    brand: "AK Signature",
    category: "Shirts",
    cloth_type: "Dress Shirt",
    color: "Jet Black",
    price: 649,
    original_price: 999,
    discount_percent: 35,
    stock: 9,
    status: "IN_STOCK",
    image: "/images/products/product_5.png",
    garment_image: "/images/garments/product_5.png",
    vton_supported: 1,
    vton_garment_category: "tops"
  },
  {
    id: 6,
    name: "Brushed Buffalo Check Flannel Shirt",
    description: "Cozy brushed double-faced flannel with understated tonal grey checks.",
    brand: "AK Heritage",
    category: "Shirts",
    cloth_type: "Checked Shirt",
    color: "Slate Check",
    price: 674,
    original_price: 899,
    discount_percent: 25,
    stock: 4,
    status: "IN_STOCK",
    image: "/images/products/product_6.png",
    garment_image: "/images/garments/product_6.png",
    vton_supported: 1,
    vton_garment_category: "tops"
  },
  {
    id: 7,
    name: "Band Collar Sand Linen Casual Shirt",
    description: "Contemporary grandad collar casual shirt in breathable pure organic linen.",
    brand: "AK Studio",
    category: "Shirts",
    cloth_type: "Linen Shirt",
    color: "Sand Beige",
    price: 639,
    original_price: 799,
    discount_percent: 20,
    stock: 8,
    status: "IN_STOCK",
    image: "/images/products/product_7.png",
    garment_image: "/images/garments/product_7.png",
    vton_supported: 1,
    vton_garment_category: "tops"
  },
  {
    id: 8,
    name: "Slate Blue Micro-Stripe Smart Shirt",
    description: "Sharp micro-stripe tailored shirt featuring reinforced French seams.",
    brand: "AK Atelier",
    category: "Shirts",
    cloth_type: "Business Shirt",
    color: "Slate Blue",
    price: 629,
    original_price: 899,
    discount_percent: 30,
    stock: 7,
    status: "IN_STOCK",
    image: "/images/products/product_8.png",
    garment_image: "/images/garments/product_8.png",
    vton_supported: 1,
    vton_garment_category: "tops"
  },
  {
    id: 9,
    name: "Washed Corduroy Overshirt Jacket",
    description: "Fine-wale tactile corduroy utility overshirt with deep chest pockets.",
    brand: "AK Urban",
    category: "Shirts",
    cloth_type: "Overshirt",
    color: "Earth Brown",
    price: 699,
    original_price: 999,
    discount_percent: 30,
    stock: 3,
    status: "IN_STOCK",
    image: "/images/products/product_9.png",
    garment_image: "/images/garments/product_9.png",
    vton_supported: 1,
    vton_garment_category: "tops"
  },
  {
    id: 10,
    name: "Pima Cotton Knit Polo Tee",
    description: "Silky mercerized Pima cotton polo with mother-of-pearl buttons.",
    brand: "AK Basics",
    category: "T-Shirts",
    cloth_type: "Polo Tee",
    color: "Steel Grey",
    price: 559,
    original_price: 699,
    discount_percent: 20,
    stock: 10,
    status: "IN_STOCK",
    image: "/images/products/product_10.png",
    garment_image: "/images/garments/product_10.png",
    vton_supported: 1,
    vton_garment_category: "tops"
  },
  {
    id: 11,
    name: "Heavyweight 240GSM Black Tee",
    description: "Durable boxy crewneck tee cut from premium carded combed cotton.",
    brand: "AK Basics",
    category: "T-Shirts",
    cloth_type: "Plain T-Shirt",
    color: "Pitch Black",
    price: 449,
    original_price: 599,
    discount_percent: 25,
    stock: 10,
    status: "IN_STOCK",
    image: "/images/products/product_11.png",
    garment_image: "/images/garments/product_11.png",
    vton_supported: 1,
    vton_garment_category: "tops"
  },
  {
    id: 12,
    name: "Minimalist Pure White Crewneck Tee",
    description: "Essential relaxed-fit everyday white tee with double-needle ribbed neckline.",
    brand: "AK Basics",
    category: "T-Shirts",
    cloth_type: "Plain T-Shirt",
    color: "Pure White",
    price: 399,
    original_price: 499,
    discount_percent: 20,
    stock: 9,
    status: "IN_STOCK",
    image: "/images/products/product_12.png",
    garment_image: "/images/garments/product_12.png",
    vton_supported: 1,
    vton_garment_category: "tops"
  },
  {
    id: 13,
    name: "Vintage Heather Grey Acid Wash Tee",
    description: "Soft lived-in feel with subtle garment stone wash and vintage patina.",
    brand: "AK Basics",
    category: "T-Shirts",
    cloth_type: "Plain T-Shirt",
    color: "Heather Grey",
    price: 467,
    original_price: 549,
    discount_percent: 15,
    stock: 8,
    status: "IN_STOCK",
    image: "/images/products/product_13.png",
    garment_image: "/images/garments/product_13.png",
    vton_supported: 1,
    vton_garment_category: "tops"
  },
  {
    id: 14,
    name: "Bauhaus Monochrome Graphic Tee",
    description: "Architectural geometric screenprint on heavyweight off-white cotton base.",
    brand: "AK Studio",
    category: "T-Shirts",
    cloth_type: "Graphic T-Shirt",
    color: "Off-White",
    price: 489,
    original_price: 699,
    discount_percent: 30,
    stock: 6,
    status: "IN_STOCK",
    image: "/images/products/product_14.png",
    garment_image: "/images/garments/product_14.png",
    vton_supported: 1,
    vton_garment_category: "tops"
  },
  {
    id: 15,
    name: "Raw Hem Charcoal Long Sleeve Tee",
    description: "Layerable thermal long-sleeve tee with thumbhole cuffs and raw edge hem.",
    brand: "AK Urban",
    category: "T-Shirts",
    cloth_type: "Long Sleeve T-Shirt",
    color: "Charcoal",
    price: 563,
    original_price: 750,
    discount_percent: 25,
    stock: 5,
    status: "IN_STOCK",
    image: "/images/products/product_15.png",
    garment_image: "/images/garments/product_15.png",
    vton_supported: 1,
    vton_garment_category: "tops"
  },
  {
    id: 16,
    name: "Drop-Shoulder Oversized Khaki Tee",
    description: "Relaxed streetwear drape with dropped shoulder seams and wide sleeves.",
    brand: "AK Studio",
    category: "T-Shirts",
    cloth_type: "Oversized T-Shirt",
    color: "Khaki",
    price: 559,
    original_price: 799,
    discount_percent: 30,
    stock: 7,
    status: "IN_STOCK",
    image: "/images/products/product_16.png",
    garment_image: "/images/garments/product_16.png",
    vton_supported: 1,
    vton_garment_category: "tops"
  },
  {
    id: 17,
    name: "Supima Cotton Deep Navy V-Neck",
    description: "Modest tailored V-neck tee made from silky Californian Supima cotton.",
    brand: "AK Basics",
    category: "T-Shirts",
    cloth_type: "V-Neck T-Shirt",
    color: "Deep Navy",
    price: 479,
    original_price: 599,
    discount_percent: 20,
    stock: 8,
    status: "IN_STOCK",
    image: "/images/products/product_17.png",
    garment_image: "/images/garments/product_17.png",
    vton_supported: 1,
    vton_garment_category: "tops"
  },
  {
    id: 18,
    name: "Waffle Texture Mocha Henley Tee",
    description: "Three-button henley tee in honeycomb waffle knit for thermal breathability.",
    brand: "AK Studio",
    category: "T-Shirts",
    cloth_type: "Henley T-Shirt",
    color: "Mocha Brown",
    price: 599,
    original_price: 799,
    discount_percent: 25,
    stock: 4,
    status: "IN_STOCK",
    image: "/images/products/product_18.png",
    garment_image: "/images/garments/product_18.png",
    vton_supported: 1,
    vton_garment_category: "tops"
  },
  {
    id: 19,
    name: "Abstract Minimal Typo Boxy Tee",
    description: "Subtle micro-typography across the chest with high-density puff ink.",
    brand: "AK Urban",
    category: "T-Shirts",
    cloth_type: "Graphic T-Shirt",
    color: "Ash Grey",
    price: 489,
    original_price: 699,
    discount_percent: 30,
    stock: 6,
    status: "IN_STOCK",
    image: "/images/products/product_19.png",
    garment_image: "/images/garments/product_19.png",
    vton_supported: 1,
    vton_garment_category: "tops"
  },
  {
    id: 20,
    name: "Heavy Jersey Ribbed Collar T-Shirt",
    description: "Structure-preserving dense knit with reinforced collar that never sags.",
    brand: "AK Basics",
    category: "T-Shirts",
    cloth_type: "Plain T-Shirt",
    color: "Dark Taupe",
    price: 499,
    original_price: 649,
    discount_percent: 23,
    stock: 7,
    status: "IN_STOCK",
    image: "/images/products/product_20.png",
    garment_image: "/images/garments/product_20.png",
    vton_supported: 1,
    vton_garment_category: "tops"
  },

  // ===================== BOTTOMS: MANDATORY EXACT 10 (21 - 30) =====================
  {
    id: 21,
    name: "Classic Charcoal Formal Trousers",
    description: "Sharply pressed wool-blend trousers with curtain waistband and clean break.",
    brand: "AK Atelier",
    category: "Pants & Trousers",
    cloth_type: "Formal Trousers",
    color: "Charcoal Grey",
    price: 629,
    original_price: 899,
    discount_percent: 30,
    stock: 10,
    status: "IN_STOCK",
    image: "/images/products/product_21.png",
    garment_image: "/images/garments/product_21.png",
    vton_supported: 1,
    vton_garment_category: "bottoms"
  },
  {
    id: 22,
    name: "Navy Casual Pants",
    description: "Comfort stretch twill trousers tailored for all-day smart-casual versatility.",
    brand: "AK Urban",
    category: "Pants & Trousers",
    cloth_type: "Casual Pants",
    color: "Navy Blue",
    price: 599,
    original_price: 799,
    discount_percent: 25,
    stock: 7,
    status: "IN_STOCK",
    image: "/images/products/product_22.png",
    garment_image: "/images/garments/product_22.png",
    vton_supported: 1,
    vton_garment_category: "bottoms"
  },
  {
    id: 23,
    name: "Black Slim-Fit Trousers",
    description: "Streamlined contemporary cut with minimal stacking and stretch flexibility.",
    brand: "AK Signature",
    category: "Pants & Trousers",
    cloth_type: "Slim-Fit Trousers",
    color: "Pitch Black",
    price: 629,
    original_price: 899,
    discount_percent: 30,
    stock: 8,
    status: "IN_STOCK",
    image: "/images/products/product_23.png",
    garment_image: "/images/garments/product_23.png",
    vton_supported: 1,
    vton_garment_category: "bottoms"
  },
  {
    id: 24,
    name: "Beige Chinos",
    description: "Classic mid-rise flat front chinos woven from combed stretch gabardine cotton.",
    brand: "AK Basics",
    category: "Pants & Trousers",
    cloth_type: "Chinos",
    color: "Warm Beige",
    price: 639,
    original_price: 799,
    discount_percent: 20,
    stock: 6,
    status: "IN_STOCK",
    image: "/images/products/product_24.png",
    garment_image: "/images/garments/product_24.png",
    vton_supported: 1,
    vton_garment_category: "bottoms"
  },
  {
    id: 25,
    name: "Taupe Cargo Pants",
    description: "Modern minimalist cargo pants featuring flush bellows pockets and tapered cuffs.",
    brand: "AK Urban",
    category: "Pants & Trousers",
    cloth_type: "Cargo Pants",
    color: "Muted Taupe",
    price: 665,
    original_price: 950,
    discount_percent: 30,
    stock: 5,
    status: "IN_STOCK",
    image: "/images/products/product_25.png",
    garment_image: "/images/garments/product_25.png",
    vton_supported: 1,
    vton_garment_category: "bottoms"
  },
  {
    id: 26,
    name: "Dark Brown Pleated Trousers",
    description: "Sartorial double-pleated front trousers with relaxed taper and buttoned side tabs.",
    brand: "AK Atelier",
    category: "Pants & Trousers",
    cloth_type: "Pleated Trousers",
    color: "Dark Brown",
    price: 674,
    original_price: 899,
    discount_percent: 25,
    stock: 4,
    status: "IN_STOCK",
    image: "/images/products/product_26.png",
    garment_image: "/images/garments/product_26.png",
    vton_supported: 1,
    vton_garment_category: "bottoms"
  },
  {
    id: 27,
    name: "Slate Grey Jogger Pants",
    description: "Refined french-terry tailored joggers with zip welt pockets and rib cuffs.",
    brand: "AK Basics",
    category: "Pants & Trousers",
    cloth_type: "Jogger Pants",
    color: "Slate Grey",
    price: 563,
    original_price: 750,
    discount_percent: 25,
    stock: 9,
    status: "IN_STOCK",
    image: "/images/products/product_27.png",
    garment_image: "/images/garments/product_27.png",
    vton_supported: 1,
    vton_garment_category: "bottoms"
  },
  {
    id: 28,
    name: "Cream Linen Pants",
    description: "Resort-ready airy linen-blend trousers with drawstring waistband and loose leg.",
    brand: "AK Studio",
    category: "Pants & Trousers",
    cloth_type: "Linen Pants",
    color: "Cream",
    price: 629,
    original_price: 899,
    discount_percent: 30,
    stock: 6,
    status: "IN_STOCK",
    image: "/images/products/product_28.png",
    garment_image: "/images/garments/product_28.png",
    vton_supported: 1,
    vton_garment_category: "bottoms"
  },
  {
    id: 29,
    name: "Stone Grey Tapered Trousers",
    description: "Structured high-density twill trousers with clean cropped hem.",
    brand: "AK Urban",
    category: "Pants & Trousers",
    cloth_type: "Tapered Trousers",
    color: "Stone Grey",
    price: 638,
    original_price: 850,
    discount_percent: 25,
    stock: 5,
    status: "IN_STOCK",
    image: "/images/products/product_29.png",
    garment_image: "/images/garments/product_29.png",
    vton_supported: 1,
    vton_garment_category: "bottoms"
  },
  {
    id: 30,
    name: "Mocha Brown Wide-Leg Trousers",
    description: "Relaxed fluid silhouette crafted for dramatic drape and modern streetwear elegance.",
    brand: "AK Studio",
    category: "Pants & Trousers",
    cloth_type: "Wide-Leg Trousers",
    color: "Mocha Brown",
    price: 665,
    original_price: 950,
    discount_percent: 30,
    stock: 3,
    status: "IN_STOCK",
    image: "/images/products/product_30.png",
    garment_image: "/images/garments/product_30.png",
    vton_supported: 1,
    vton_garment_category: "bottoms"
  },

  // ===================== TOPS: HOODIES (31 - 40) =====================
  {
    id: 31,
    name: "Heavy French Terry Grey Hoodie",
    description: "Thick 400GSM french terry fleece hoodie with double-lined hood and metal aglets.",
    brand: "AK Basics",
    category: "Hoodies",
    cloth_type: "Pullover Hoodie",
    color: "Heather Grey",
    price: 649,
    original_price: 999,
    discount_percent: 35,
    stock: 7,
    status: "IN_STOCK",
    image: "/images/products/product_31.png",
    garment_image: "/images/garments/product_31.png",
    vton_supported: 1,
    vton_garment_category: "tops"
  },
  {
    id: 32,
    name: "Deep Navy Thermal Fleece Hoodie",
    description: "Insulated plush fleece inner layer with kangaroo pocket and ribbed cuffs.",
    brand: "AK Studio",
    category: "Hoodies",
    cloth_type: "Pullover Hoodie",
    color: "Deep Navy",
    price: 665,
    original_price: 950,
    discount_percent: 30,
    stock: 6,
    status: "IN_STOCK",
    image: "/images/products/product_32.png",
    garment_image: "/images/garments/product_32.png",
    vton_supported: 1,
    vton_garment_category: "tops"
  },
  {
    id: 33,
    name: "Minimalist Abstract Printed Hoodie",
    description: "Monochrome architectural lines on soft garment-dyed off-white fleece.",
    brand: "AK Studio",
    category: "Hoodies",
    cloth_type: "Printed Hoodie",
    color: "Off-White",
    price: 649,
    original_price: 999,
    discount_percent: 35,
    stock: 5,
    status: "IN_STOCK",
    image: "/images/products/product_33.png",
    garment_image: "/images/garments/product_33.png",
    vton_supported: 1,
    vton_garment_category: "tops"
  },
  {
    id: 34,
    name: "Boxy Drop-Shoulder Oversized Hoodie",
    description: "Wide streetwear proportions with seamless shoulders and heavyweight drape.",
    brand: "AK Urban",
    category: "Hoodies",
    cloth_type: "Oversized Hoodie",
    color: "Charcoal Grey",
    price: 699,
    original_price: 999,
    discount_percent: 30,
    stock: 8,
    status: "IN_STOCK",
    image: "/images/products/product_34.png",
    garment_image: "/images/garments/product_34.png",
    vton_supported: 1,
    vton_garment_category: "tops"
  },
  {
    id: 35,
    name: "Deep Maroon Brushed Cotton Hoodie",
    description: "Rich winter tone hoodie with peached cotton finish for velvety hand feel.",
    brand: "AK Heritage",
    category: "Hoodies",
    cloth_type: "Pullover Hoodie",
    color: "Deep Maroon",
    price: 674,
    original_price: 899,
    discount_percent: 25,
    stock: 4,
    status: "IN_STOCK",
    image: "/images/products/product_35.png",
    garment_image: "/images/garments/product_35.png",
    vton_supported: 1,
    vton_garment_category: "tops"
  },
  {
    id: 36,
    name: "Monochrome Colour Block Hoodie",
    description: "Sleek geometric horizontal panels combining black, slate, and ash grey.",
    brand: "AK Studio",
    category: "Hoodies",
    cloth_type: "Colour Block Hoodie",
    color: "Black & Grey",
    price: 699,
    original_price: 999,
    discount_percent: 30,
    stock: 6,
    status: "IN_STOCK",
    image: "/images/products/product_36.png",
    garment_image: "/images/garments/product_36.png",
    vton_supported: 1,
    vton_garment_category: "tops"
  },
  {
    id: 37,
    name: "Tactical Olive Full-Zip Hoodie",
    description: "Heavy two-way YKK matte zip with reinforced forearm patches and side vents.",
    brand: "AK Urban",
    category: "Hoodies",
    cloth_type: "Zip-Up Hoodie",
    color: "Muted Olive",
    price: 649,
    original_price: 999,
    discount_percent: 35,
    stock: 5,
    status: "IN_STOCK",
    image: "/images/products/product_37.png",
    garment_image: "/images/garments/product_37.png",
    vton_supported: 1,
    vton_garment_category: "tops"
  },
  {
    id: 38,
    name: "Sand Stone Relaxed Fleece Hoodie",
    description: "Earthy neutral hoodie cut with generous room for easy fall layering.",
    brand: "AK Studio",
    category: "Hoodies",
    cloth_type: "Pullover Hoodie",
    color: "Sand Stone",
    price: 629,
    original_price: 899,
    discount_percent: 30,
    stock: 7,
    status: "IN_STOCK",
    image: "/images/products/product_38.png",
    garment_image: "/images/garments/product_38.png",
    vton_supported: 1,
    vton_garment_category: "tops"
  },
  {
    id: 39,
    name: "Vintage Mineral Wash Dark Grey Hoodie",
    description: "Unique cloud-wash distress finish with raw edge pocket seams.",
    brand: "AK Heritage",
    category: "Hoodies",
    cloth_type: "Washed Hoodie",
    color: "Mineral Grey",
    price: 699,
    original_price: 999,
    discount_percent: 30,
    stock: 3,
    status: "IN_STOCK",
    image: "/images/products/product_39.png",
    garment_image: "/images/garments/product_39.png",
    vton_supported: 1,
    vton_garment_category: "tops"
  },
  {
    id: 40,
    name: "Minimalist Raglan Sleeve Cream Hoodie",
    description: "Seamless neck-to-arm athletic cut hoodie in warm natural unbleached cream.",
    brand: "AK Basics",
    category: "Hoodies",
    cloth_type: "Pullover Hoodie",
    color: "Natural Cream",
    price: 629,
    original_price: 899,
    discount_percent: 30,
    stock: 9,
    status: "IN_STOCK",
    image: "/images/products/product_40.png",
    garment_image: "/images/garments/product_40.png",
    vton_supported: 1,
    vton_garment_category: "tops"
  },

  // ===================== TOPS: JACKETS (41 - 50) =====================
  {
    id: 41,
    name: "Vintage Wash Classic Denim Jacket",
    description: "Timeless 13.5oz denim trucker with brass shanks and chest flap pockets.",
    brand: "AK Heritage",
    category: "Jackets",
    cloth_type: "Denim Jacket",
    color: "Washed Indigo",
    price: 699,
    original_price: 999,
    discount_percent: 30,
    stock: 5,
    status: "IN_STOCK",
    image: "/images/products/product_41.png",
    garment_image: "/images/garments/product_41.png",
    vton_supported: 1,
    vton_garment_category: "tops"
  },
  {
    id: 42,
    name: "Matte Black Tactical Bomber Jacket",
    description: "Flight nylon outer shell with orange emergency liner and utility sleeve pocket.",
    brand: "AK Urban",
    category: "Jackets",
    cloth_type: "Bomber Jacket",
    color: "Matte Black",
    price: 699,
    original_price: 999,
    discount_percent: 30,
    stock: 6,
    status: "IN_STOCK",
    image: "/images/products/product_42.png",
    garment_image: "/images/garments/product_42.png",
    vton_supported: 1,
    vton_garment_category: "tops"
  },
  {
    id: 43,
    name: "Quilted Ultralight Puffer Jacket",
    description: "Water-repellent thermal down-alternative baffles for compact warmth.",
    brand: "AK Studio",
    category: "Jackets",
    cloth_type: "Quilted Puffer Jacket",
    color: "Charcoal Grey",
    price: 699,
    original_price: 999,
    discount_percent: 30,
    stock: 4,
    status: "IN_STOCK",
    image: "/images/products/product_43.png",
    garment_image: "/images/garments/product_43.png",
    vton_supported: 1,
    vton_garment_category: "tops"
  },
  {
    id: 44,
    name: "Heritage Wool-Blend Varsity Jacket",
    description: "Classic snap-button letterman jacket with leather-trimmed welt pockets.",
    brand: "AK Heritage",
    category: "Jackets",
    cloth_type: "Varsity Jacket",
    color: "Navy & Grey",
    price: 699,
    original_price: 999,
    discount_percent: 30,
    stock: 5,
    status: "IN_STOCK",
    image: "/images/products/product_44.png",
    garment_image: "/images/garments/product_44.png",
    vton_supported: 1,
    vton_garment_category: "tops"
  },
  {
    id: 45,
    name: "Asymmetric Ashen Faux Biker Jacket",
    description: "Matte textured moto jacket with heavy hardware and snap lapels.",
    brand: "AK Urban",
    category: "Jackets",
    cloth_type: "Biker Jacket",
    color: "Ashen Charcoal",
    price: 699,
    original_price: 999,
    discount_percent: 30,
    stock: 3,
    status: "IN_STOCK",
    image: "/images/products/product_45.png",
    garment_image: "/images/garments/product_45.png",
    vton_supported: 1,
    vton_garment_category: "tops"
  },
  {
    id: 46,
    name: "Water-Resistant Windbreaker Jacket",
    description: "Breathable ripstop nylon shell with stowable hood and adjustable toggle hem.",
    brand: "AK Basics",
    category: "Jackets",
    cloth_type: "Windbreaker",
    color: "Pitch Black",
    price: 674,
    original_price: 899,
    discount_percent: 25,
    stock: 8,
    status: "IN_STOCK",
    image: "/images/products/product_46.png",
    garment_image: "/images/garments/product_46.png",
    vton_supported: 1,
    vton_garment_category: "tops"
  },
  {
    id: 47,
    name: "Safari Utility Field Jacket",
    description: "Four-pocket tactical military field coat with hidden drawcord waist.",
    brand: "AK Heritage",
    category: "Jackets",
    cloth_type: "Field Jacket",
    color: "Desert Khaki",
    price: 699,
    original_price: 999,
    discount_percent: 30,
    stock: 4,
    status: "IN_STOCK",
    image: "/images/products/product_47.png",
    garment_image: "/images/garments/product_47.png",
    vton_supported: 1,
    vton_garment_category: "tops"
  },
  {
    id: 48,
    name: "Minimalist Harrington Casual Jacket",
    description: "Clean stand collar jacket with ribbed trim and classic tartan inner lining.",
    brand: "AK Studio",
    category: "Jackets",
    cloth_type: "Harrington Jacket",
    color: "Navy Blue",
    price: 699,
    original_price: 999,
    discount_percent: 30,
    stock: 6,
    status: "IN_STOCK",
    image: "/images/products/product_48.png",
    garment_image: "/images/garments/product_48.png",
    vton_supported: 1,
    vton_garment_category: "tops"
  },
  {
    id: 49,
    name: "Coach Snap-Button Trench Jacket",
    description: "Modern street jacket with sharp point collar and tonal matte snap closures.",
    brand: "AK Urban",
    category: "Jackets",
    cloth_type: "Coach Jacket",
    color: "Stone Grey",
    price: 674,
    original_price: 899,
    discount_percent: 25,
    stock: 7,
    status: "IN_STOCK",
    image: "/images/products/product_49.png",
    garment_image: "/images/garments/product_49.png",
    vton_supported: 1,
    vton_garment_category: "tops"
  },
  {
    id: 50,
    name: "Corduroy Collar Workwear Jacket",
    description: "Rugged heavyweight duck canvas chore coat with brass riveted stress points.",
    brand: "AK Heritage",
    category: "Jackets",
    cloth_type: "Workwear Jacket",
    color: "Tobacco Brown",
    price: 699,
    original_price: 999,
    discount_percent: 30,
    stock: 0,
    status: "SOLD_OUT",
    image: "/images/products/product_50.png",
    garment_image: "/images/garments/product_50.png",
    vton_supported: 1,
    vton_garment_category: "tops"
  },

  // ===================== ACCESSORIES: SHOES (51 - 60) =====================
  {
    id: 51,
    name: "Classic White Leather Low Sneakers",
    description: "Minimalist tennis silhouette crafted from supple full-grain Italian leather.",
    brand: "AK Signature",
    category: "Shoes",
    cloth_type: "Sneakers",
    color: "Crisp White",
    price: 699,
    original_price: 999,
    discount_percent: 30,
    stock: 8,
    status: "IN_STOCK",
    image: "/images/products/product_51.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 52,
    name: "Minimalist Black Canvas Skate Shoes",
    description: "Low-profile vulcanized rubber sole with reinforced toe cap and padded collar.",
    brand: "AK Urban",
    category: "Shoes",
    cloth_type: "Skate Shoes",
    color: "Pitch Black",
    price: 599,
    original_price: 799,
    discount_percent: 25,
    stock: 10,
    status: "IN_STOCK",
    image: "/images/products/product_52.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 53,
    name: "Suede Chelsea Boots in Sand",
    description: "Supple water-resistant split suede with elasticated side gussets and crepe sole.",
    brand: "AK Studio",
    category: "Shoes",
    cloth_type: "Chelsea Boots",
    color: "Sand Beige",
    price: 699,
    original_price: 999,
    discount_percent: 30,
    stock: 4,
    status: "IN_STOCK",
    image: "/images/products/product_53.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 54,
    name: "Leather Penny Loafers in Dark Brown",
    description: "Hand-stitched apron toe loafers in burnished calfskin with leather outsole.",
    brand: "AK Atelier",
    category: "Shoes",
    cloth_type: "Penny Loafers",
    color: "Dark Brown",
    price: 699,
    original_price: 999,
    discount_percent: 30,
    stock: 5,
    status: "IN_STOCK",
    image: "/images/products/product_54.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 55,
    name: "Breathable Mesh Running Trainers",
    description: "Engineered mesh upper paired with responsive EVA cushioning for daily comfort.",
    brand: "AK Basics",
    category: "Shoes",
    cloth_type: "Trainers",
    color: "Cool Grey",
    price: 649,
    original_price: 899,
    discount_percent: 28,
    stock: 7,
    status: "IN_STOCK",
    image: "/images/products/product_55.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 56,
    name: "Formal Oxford Dress Shoes in Black",
    description: "Closed-laced cap toe formal dress shoes with high-gloss mirror finish.",
    brand: "AK Atelier",
    category: "Shoes",
    cloth_type: "Oxford Shoes",
    color: "Gloss Black",
    price: 699,
    original_price: 999,
    discount_percent: 30,
    stock: 3,
    status: "IN_STOCK",
    image: "/images/products/product_56.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 57,
    name: "Retro High-Top Court Sneakers",
    description: "Vintage basketball heritage sneaker with padded ankle collar and pivot-point sole.",
    brand: "AK Urban",
    category: "Shoes",
    cloth_type: "High-Tops",
    color: "White & Navy",
    price: 699,
    original_price: 999,
    discount_percent: 30,
    stock: 6,
    status: "IN_STOCK",
    image: "/images/products/product_57.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 58,
    name: "Leather Driving Moccasins",
    description: "Supple pebble-grain leather with rubber nubbed driving sole and raw lace detail.",
    brand: "AK Studio",
    category: "Shoes",
    cloth_type: "Driving Shoes",
    color: "Tan Brown",
    price: 629,
    original_price: 899,
    discount_percent: 30,
    stock: 5,
    status: "IN_STOCK",
    image: "/images/products/product_58.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 59,
    name: "Chunky Sole Casual Derby Shoes",
    description: "Modernized postman derby with exaggerated commando lug sole and matte leather.",
    brand: "AK Urban",
    category: "Shoes",
    cloth_type: "Derby Shoes",
    color: "Matte Black",
    price: 699,
    original_price: 999,
    discount_percent: 30,
    stock: 2,
    status: "IN_STOCK",
    image: "/images/products/product_59.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 60,
    name: "Navy Canvas Slip-On Espadrilles",
    description: "Braided jute rope sole reinforced with durable rubber base for summer lounging.",
    brand: "AK Studio",
    category: "Shoes",
    cloth_type: "Espadrilles",
    color: "Navy Blue",
    price: 499,
    original_price: 699,
    discount_percent: 29,
    stock: 9,
    status: "IN_STOCK",
    image: "/images/products/product_60.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },

  // ===================== ACCESSORIES: WATCHES (61 - 70) =====================
  {
    id: 61,
    name: "Minimalist Matte Black Mesh Watch",
    description: "Ultra-slim 7mm case with sunray dial and magnetic Milanese steel mesh strap.",
    brand: "AK Signature",
    category: "Watches",
    cloth_type: "Minimalist Watch",
    color: "Matte Black",
    price: 599,
    original_price: 899,
    discount_percent: 33,
    stock: 10,
    status: "IN_STOCK",
    image: "/images/products/product_61.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 62,
    name: "Silver Chronograph Leather Strap Watch",
    description: "Three sub-dial chronograph with sapphire coated crystal and top-grain brown leather.",
    brand: "AK Atelier",
    category: "Watches",
    cloth_type: "Chronograph",
    color: "Brown & Silver",
    price: 699,
    original_price: 999,
    discount_percent: 30,
    stock: 7,
    status: "IN_STOCK",
    image: "/images/products/product_62.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 63,
    name: "Bauhaus White Dial Minimalist Watch",
    description: "Clean typography dial inspired by mid-century modern design with date window.",
    brand: "AK Studio",
    category: "Watches",
    cloth_type: "Dress Watch",
    color: "White & Silver",
    price: 549,
    original_price: 799,
    discount_percent: 31,
    stock: 8,
    status: "IN_STOCK",
    image: "/images/products/product_63.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 64,
    name: "Gunmetal Steel Link Bracelet Watch",
    description: "Brushed gunmetal solid link bracelet with Japanese quartz precision movement.",
    brand: "AK Urban",
    category: "Watches",
    cloth_type: "Steel Watch",
    color: "Gunmetal",
    price: 699,
    original_price: 999,
    discount_percent: 30,
    stock: 5,
    status: "IN_STOCK",
    image: "/images/products/product_64.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 65,
    name: "Vintage Gold-Tone Dress Watch",
    description: "Warm gold-plated bezel paired with embossed black crocodile leather strap.",
    brand: "AK Heritage",
    category: "Watches",
    cloth_type: "Vintage Watch",
    color: "Gold & Black",
    price: 649,
    original_price: 899,
    discount_percent: 28,
    stock: 6,
    status: "IN_STOCK",
    image: "/images/products/product_65.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 66,
    name: "Tactical Dual-Time Field Watch",
    description: "High-contrast luminescent markers with rugged ballistic nylon NATO strap.",
    brand: "AK Urban",
    category: "Watches",
    cloth_type: "Field Watch",
    color: "Olive & Black",
    price: 599,
    original_price: 850,
    discount_percent: 30,
    stock: 7,
    status: "IN_STOCK",
    image: "/images/products/product_66.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 67,
    name: "Minimalist Pilot Aviation Quartz Watch",
    description: "Matte black case with oversized onion crown and bold utilitarian numeral display.",
    brand: "AK Basics",
    category: "Watches",
    cloth_type: "Pilot Watch",
    color: "Matte Black",
    price: 529,
    original_price: 750,
    discount_percent: 29,
    stock: 9,
    status: "IN_STOCK",
    image: "/images/products/product_67.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 68,
    name: "Rose Gold Accent Leather Watch",
    description: "Subtle brushed rose gold accents framing a deep midnight blue sunray dial.",
    brand: "AK Studio",
    category: "Watches",
    cloth_type: "Dress Watch",
    color: "Rose Gold & Navy",
    price: 649,
    original_price: 899,
    discount_percent: 28,
    stock: 4,
    status: "IN_STOCK",
    image: "/images/products/product_68.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 69,
    name: "Titanium-Finish Slimline Watch",
    description: "Lightweight titanium-toned sandblasted case with water resistance up to 50M.",
    brand: "AK Signature",
    category: "Watches",
    cloth_type: "Slim Watch",
    color: "Titanium Grey",
    price: 699,
    original_price: 999,
    discount_percent: 30,
    stock: 6,
    status: "IN_STOCK",
    image: "/images/products/product_69.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 70,
    name: "Retro Digital Steel Watch",
    description: "Vintage 1980s aesthetic with electro-luminescent backlight and daily alarm.",
    brand: "AK Basics",
    category: "Watches",
    cloth_type: "Digital Watch",
    color: "Silver Steel",
    price: 449,
    original_price: 599,
    discount_percent: 25,
    stock: 8,
    status: "IN_STOCK",
    image: "/images/products/product_70.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },

  // ===================== ACCESSORIES: CAPS (71 - 80) =====================
  {
    id: 71,
    name: "Washed Cotton Low-Profile Dad Cap",
    description: "Unstructured 6-panel twill cap with brass strap buckle and pre-curved visor.",
    brand: "AK Basics",
    category: "Caps",
    cloth_type: "Baseball Cap",
    color: "Washed Black",
    price: 349,
    original_price: 499,
    discount_percent: 30,
    stock: 10,
    status: "IN_STOCK",
    image: "/images/products/product_71.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 72,
    name: "Structured Twill Snapback Cap",
    description: "High-crown urban snapback cap with flat visor and tonal embroidered eyelets.",
    brand: "AK Urban",
    category: "Caps",
    cloth_type: "Snapback Cap",
    color: "Charcoal Grey",
    price: 399,
    original_price: 599,
    discount_percent: 33,
    stock: 8,
    status: "IN_STOCK",
    image: "/images/products/product_72.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 73,
    name: "Merino Wool Blend Minimalist Beanie",
    description: "Fine knit ribbed beanie with adjustable roll-up brim for lightweight thermal warmth.",
    brand: "AK Basics",
    category: "Caps",
    cloth_type: "Beanie",
    color: "Heather Grey",
    price: 299,
    original_price: 399,
    discount_percent: 25,
    stock: 9,
    status: "IN_STOCK",
    image: "/images/products/product_73.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 74,
    name: "Classic Navy Curved Brim Baseball Cap",
    description: "Mid-profile structured fit with sweat-wicking internal headband.",
    brand: "AK Signature",
    category: "Caps",
    cloth_type: "Baseball Cap",
    color: "Navy Blue",
    price: 349,
    original_price: 499,
    discount_percent: 30,
    stock: 7,
    status: "IN_STOCK",
    image: "/images/products/product_74.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 75,
    name: "Vintage Corduroy Unstructured Cap",
    description: "8-wale plush corduroy cap with self-fabric adjustable strap and metal grommet.",
    brand: "AK Heritage",
    category: "Caps",
    cloth_type: "Corduroy Cap",
    color: "Tan Brown",
    price: 449,
    original_price: 599,
    discount_percent: 25,
    stock: 6,
    status: "IN_STOCK",
    image: "/images/products/product_75.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 76,
    name: "Suede-Finish Streetwear Cap",
    description: "Buttery faux-suede crown featuring laser-cut ventilation ports.",
    brand: "AK Urban",
    category: "Caps",
    cloth_type: "Suede Cap",
    color: "Muted Olive",
    price: 499,
    original_price: 699,
    discount_percent: 29,
    stock: 5,
    status: "IN_STOCK",
    image: "/images/products/product_76.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 77,
    name: "Ultralight Performance Runner Cap",
    description: "Quick-drying UPF 50+ athletic cap with reflective safety accents.",
    brand: "AK Basics",
    category: "Caps",
    cloth_type: "Sports Cap",
    color: "Pure White",
    price: 379,
    original_price: 499,
    discount_percent: 24,
    stock: 8,
    status: "IN_STOCK",
    image: "/images/products/product_77.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 78,
    name: "Ribbed Knit Short Fisherman Beanie",
    description: "Snug above-the-ears sailor fit crafted from durable organic acrylic wool yarn.",
    brand: "AK Studio",
    category: "Caps",
    cloth_type: "Beanie",
    color: "Pitch Black",
    price: 329,
    original_price: 449,
    discount_percent: 27,
    stock: 10,
    status: "IN_STOCK",
    image: "/images/products/product_78.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 79,
    name: "Houndstooth Newsboy Ivy Flat Cap",
    description: "Traditional 8-piece panel flat cap with satin lining and concealed snap brim.",
    brand: "AK Heritage",
    category: "Caps",
    cloth_type: "Flat Cap",
    color: "Grey Houndstooth",
    price: 499,
    original_price: 699,
    discount_percent: 29,
    stock: 4,
    status: "IN_STOCK",
    image: "/images/products/product_79.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 80,
    name: "Weatherproof 5-Panel Camper Cap",
    description: "Low-profile nylon camper cap with webbed nylon clip strap.",
    brand: "AK Urban",
    category: "Caps",
    cloth_type: "5-Panel Cap",
    color: "Slate Grey",
    price: 429,
    original_price: 599,
    discount_percent: 28,
    stock: 6,
    status: "IN_STOCK",
    image: "/images/products/product_80.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },

  // ===================== ACCESSORIES: BELTS (81 - 90) =====================
  {
    id: 81,
    name: "Full Grain Leather Dress Belt",
    description: "32mm width formal leather belt with feather-edge stitching and zinc buckle.",
    brand: "AK Signature",
    category: "Belts",
    cloth_type: "Formal Belt",
    color: "Classic Black",
    price: 499,
    original_price: 699,
    discount_percent: 29,
    stock: 9,
    status: "IN_STOCK",
    image: "/images/products/product_81.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 82,
    name: "Reversible Tan to Black Leather Belt",
    description: "Twist-action buckle mechanism allowing effortless switching between black and tan.",
    brand: "AK Atelier",
    category: "Belts",
    cloth_type: "Reversible Belt",
    color: "Tan & Black",
    price: 599,
    original_price: 799,
    discount_percent: 25,
    stock: 8,
    status: "IN_STOCK",
    image: "/images/products/product_82.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 83,
    name: "Braided Stretch Fabric Casual Belt",
    description: "Flexible woven braided strap offering infinite micro-adjustment without holes.",
    brand: "AK Basics",
    category: "Belts",
    cloth_type: "Braided Belt",
    color: "Navy & Brown",
    price: 399,
    original_price: 549,
    discount_percent: 27,
    stock: 10,
    status: "IN_STOCK",
    image: "/images/products/product_83.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 84,
    name: "Distressed Suede Casual Jean Belt",
    description: "38mm rugged suede leather belt with antique silver harness buckle.",
    brand: "AK Heritage",
    category: "Belts",
    cloth_type: "Casual Belt",
    color: "Chocolate Brown",
    price: 549,
    original_price: 749,
    discount_percent: 27,
    stock: 6,
    status: "IN_STOCK",
    image: "/images/products/product_84.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 85,
    name: "Matte Gunmetal Buckle Leather Belt",
    description: "Sleek squared buckle with brushed gunmetal finish and oil-tanned leather strap.",
    brand: "AK Urban",
    category: "Belts",
    cloth_type: "Dress Belt",
    color: "Dark Charcoal",
    price: 529,
    original_price: 699,
    discount_percent: 24,
    stock: 7,
    status: "IN_STOCK",
    image: "/images/products/product_85.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 86,
    name: "Military Spec Tactical Webbing Belt",
    description: "Heavy-duty nylon webbing paired with quick-release alloy friction slider.",
    brand: "AK Urban",
    category: "Belts",
    cloth_type: "Web Belt",
    color: "Tactical Olive",
    price: 349,
    original_price: 499,
    discount_percent: 30,
    stock: 10,
    status: "IN_STOCK",
    image: "/images/products/product_86.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 87,
    name: "Minimalist Stitch-Detail Brown Belt",
    description: "Subtle ecru thread edge stitching on vegetable-tanned full grain cowhide.",
    brand: "AK Studio",
    category: "Belts",
    cloth_type: "Leather Belt",
    color: "Mocha Brown",
    price: 489,
    original_price: 649,
    discount_percent: 25,
    stock: 5,
    status: "IN_STOCK",
    image: "/images/products/product_87.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 88,
    name: "Automatic Ratchet Click Belt",
    description: "Holeless 32-step micro-adjustable track belt for an exact tailored fit.",
    brand: "AK Signature",
    category: "Belts",
    cloth_type: "Ratchet Belt",
    color: "Pitch Black",
    price: 599,
    original_price: 799,
    discount_percent: 25,
    stock: 6,
    status: "IN_STOCK",
    image: "/images/products/product_88.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 89,
    name: "Textured Saffiano Italian Leather Belt",
    description: "Crosshatch scratch-resistant saffiano calfskin with polished silver buckle.",
    brand: "AK Atelier",
    category: "Belts",
    cloth_type: "Luxury Belt",
    color: "Deep Brown",
    price: 649,
    original_price: 899,
    discount_percent: 28,
    stock: 4,
    status: "IN_STOCK",
    image: "/images/products/product_89.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 90,
    name: "Vintage Double-Prong Workwear Belt",
    description: "Extra-wide 40mm thick bridle leather belt with heavy dual-prong roller buckle.",
    brand: "AK Heritage",
    category: "Belts",
    cloth_type: "Vintage Belt",
    color: "Antique Brown",
    price: 549,
    original_price: 750,
    discount_percent: 27,
    stock: 0,
    status: "SOLD_OUT",
    image: "/images/products/product_90.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },

  // ===================== ACCESSORIES: SUNGLASSES (91 - 100) =====================
  {
    id: 91,
    name: "Polarized Classic Wayfarer Sunglasses",
    description: "Timeless trapezoidal acetate frame with 100% UV400 polarized dark lenses.",
    brand: "AK Signature",
    category: "Sunglasses",
    cloth_type: "Wayfarer",
    color: "Matte Black",
    price: 599,
    original_price: 899,
    discount_percent: 33,
    stock: 10,
    status: "IN_STOCK",
    image: "/images/products/product_91.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 92,
    name: "Aviator Metal Teardrop Sunglasses",
    description: "Ultralight stainless steel double-bridge frame with smoke grey tinted glass.",
    brand: "AK Basics",
    category: "Sunglasses",
    cloth_type: "Aviator",
    color: "Silver & Smoke Grey",
    price: 649,
    original_price: 899,
    discount_percent: 28,
    stock: 8,
    status: "IN_STOCK",
    image: "/images/products/product_92.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 93,
    name: "Vintage Round Tortoise Shell Shades",
    description: "Circular keyhole bridge sunglasses made from hand-polished Italian acetate.",
    brand: "AK Heritage",
    category: "Sunglasses",
    cloth_type: "Round Frame",
    color: "Dark Tortoise",
    price: 599,
    original_price: 850,
    discount_percent: 30,
    stock: 7,
    status: "IN_STOCK",
    image: "/images/products/product_93.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 94,
    name: "Modern Clubmaster Browline Sunglasses",
    description: "Bold acetate browline anchored by a slim gold-toned metal lens under-rim.",
    brand: "AK Studio",
    category: "Sunglasses",
    cloth_type: "Browline",
    color: "Black & Gold",
    price: 629,
    original_price: 899,
    discount_percent: 30,
    stock: 6,
    status: "IN_STOCK",
    image: "/images/products/product_94.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 95,
    name: "Geometric Hexagonal Metal Sunglasses",
    description: "Architectural six-sided slim metal frame with glare-reducing mirror coating.",
    brand: "AK Urban",
    category: "Sunglasses",
    cloth_type: "Geometric",
    color: "Gunmetal",
    price: 599,
    original_price: 799,
    discount_percent: 25,
    stock: 5,
    status: "IN_STOCK",
    image: "/images/products/product_95.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 96,
    name: "Minimalist Rimless Polarized Shades",
    description: "Featherweight rimless construction with screw-mounted anti-scratch lenses.",
    brand: "AK Signature",
    category: "Sunglasses",
    cloth_type: "Rimless",
    color: "Charcoal Grey",
    price: 549,
    original_price: 749,
    discount_percent: 27,
    stock: 8,
    status: "IN_STOCK",
    image: "/images/products/product_96.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 97,
    name: "Flat-Top Modern Shield Sunglasses",
    description: "Futuristic seamless single-lens shield with straight horizontal brow line.",
    brand: "AK Urban",
    category: "Sunglasses",
    cloth_type: "Shield",
    color: "Gloss Black",
    price: 499,
    original_price: 699,
    discount_percent: 29,
    stock: 9,
    status: "IN_STOCK",
    image: "/images/products/product_97.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 98,
    name: "Gradient Lens Pilot Sunglasses",
    description: "Warm amber gradient lenses housed in a brushed champagne gold alloy frame.",
    brand: "AK Atelier",
    category: "Sunglasses",
    cloth_type: "Pilot",
    color: "Gold & Amber",
    price: 649,
    original_price: 899,
    discount_percent: 28,
    stock: 4,
    status: "IN_STOCK",
    image: "/images/products/product_98.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 99,
    name: "Retro Square Acetate Sunglasses",
    description: "Thick blocky square frames with beveled temples and 7-barrel hinges.",
    brand: "AK Studio",
    category: "Sunglasses",
    cloth_type: "Square Frame",
    color: "Slate Grey",
    price: 599,
    original_price: 799,
    discount_percent: 25,
    stock: 6,
    status: "IN_STOCK",
    image: "/images/products/product_99.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  },
  {
    id: 100,
    name: "Outdoor UV400 Sport Wrap Sunglasses",
    description: "Ergonomic aerodynamic wrap-around frame with non-slip rubber nose pads.",
    brand: "AK Basics",
    category: "Sunglasses",
    cloth_type: "Sport Sunglasses",
    color: "Matte Navy",
    price: 529,
    original_price: 749,
    discount_percent: 29,
    stock: 7,
    status: "IN_STOCK",
    image: "/images/products/product_100.png",
    garment_image: null,
    vton_supported: 0,
    vton_garment_category: null
  }
];
